version = 1

[formatters]
simple.format = '%(asctime)s | %(name)s | %(levelname)-5s | %(message)s'

[handlers]
[handlers.console]
class = 'logging.StreamHandler'
level = 'DEBUG'
formatter = 'simple'
stream = 'ext://sys.stdout'
[handlers.file]
class = 'logging.StreamHandler'
level = 'ERROR'
formatter = 'simple'
stream = 'ext://sys.stderr'

[loggers.log]
level = 'DEBUG'
handlers = ['console']
propagate = 'yes'

[root]
level = 'DEBUG'
handlers = ['file']
